#!/bin/bash

start() {
    if !pidof dionaea >& /dev/null
    then
        ## Program is running, exit with error.
        echo "Error! Dionaea is currently running!" 1>&2
        exit 1
    else
        p0f -i any -u root -Q /tmp/p0f.sock -q -l -d -o /dev/null -c 1024
        sleep 1
        chown nobody:nogroup /tmp/p0f.sock
        sleep 1
        /opt/dionaea/bin/dionaea -u nobody -g nogroup -D
    fi
}

stop() {
    if pidof dionaea >& /dev/null
    then
        ## Program is running, so stop it
        killall p0f  >& /dev/null
        killall dionaea  >& /dev/null
        echo "Dionaea stopped"
    else
        ## Program is not running, exit with error.
        echo "Error! Dionaea not started!" 1>&2
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac