#!/bin/bash

PIDFILE=/home/kippo/kippo/kippo.pid

start() {
	if [ -e $PIDFILE ]; then
		if ps -p $(cat /home/kippo/kippo/kippo.pid) > /dev/null 
		then
			## Program is running, exit with error.
			echo "Error! Kippo is currently running!" 1>&2
			exit 1
		else
			cd /home/kippo/kippo
			sudo -u kippo -H sh -c "~/kippo/start.sh"
		fi
    else
		cd /home/kippo/kippo
        sudo -u kippo -H sh -c "~/kippo/start.sh"
    fi
}

stop() {
    if [ -e $PIDFILE ]; then
		if ps -p $(cat /home/kippo/kippo/kippo.pid) > /dev/null 
		then
        ## Program is running, so stop it
        kill -9 $(cat /home/kippo/kippo/kippo.pid)  >& /dev/null
        echo "Kippo stopped"
		else
			## Program is not running, exit with error.
			echo "Error! Kippo not started!" 1>&2
			exit 1
		fi
    else
        ## Program is not running, exit with error.
        echo "Error! Kippo not started!" 1>&2
        exit 1
    fi
}

## Check to see if we are running as root first.
## Found at http://www.cyberciti.biz/tips/shell-root-user-check-script.html
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root" 1>&2
    exit 1
fi

case "$1" in
    start)
        start
        exit 0
    ;;
    stop)
        stop
        exit 0
    ;;
    reload|restart|force-reload)
        stop
        start
        exit 0
    ;;
    **)
        echo "Usage: $0 {start|stop|reload}" 1>&2
        exit 1
    ;;
esac